<?php

defined("FID_JP_TANPAPERLUASAN") OR define("FID_JP_TANPAPERLUASAN", 1);
defined("FID_JP_BANJIR") OR define("FID_JP_BANJIR", 2);
defined("FID_JP_KERUSUHAN") OR define("FID_JP_KERUSUHAN", 3);
defined("FID_JP_RISIKOLAIN") OR define("FID_JP_RISIKOLAIN", 4);
defined("FID_JP_BANJIRKERUSUHAN") OR define("FID_JP_BANJIRKERUSUHAN", 5);
defined("FID_JP_BANJIRRISIKOLAIN") OR define("FID_JP_BANJIRRISIKOLAIN", 6);
defined("FID_JP_KERUSUHANRISIKOLAIN") OR define("FID_JP_KERUSUHANRISIKOLAIN", 7);
defined("FID_JP_SEMUAPERLUASAN") OR define("FID_JP_SEMUAPERLUASAN", 8);